### ISSUE TITLE
[BUG] 500 Internal Server Error

### ISSUE THREAD

**Issue by seirdotexe** [benbusby/whoogle-search#1050]
**Describe the bug**
When you search for **Mathias Normann**, you get error code 500. It doesn't happen when you search for **Mathias Normannaaa**.

**To Reproduce**
1. Search on your Whoogle instance for **Mathias Normann**.

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version 0.8.2
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: FireFox Developer Edition
 - Version 117.0b5 (64-bit)

**Additional context**
```
08/10/2023 4:21:21 PM
ERROR:app:Exception on /search [POST]
08/10/2023 4:21:21 PM
Traceback (most recent call last):
08/10/2023 4:21:21 PM
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
08/10/2023 4:21:21 PM
    response = self.full_dispatch_request()
08/10/2023 4:21:21 PM
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08/10/2023 4:21:21 PM
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
08/10/2023 4:21:21 PM
    rv = self.handle_user_exception(e)
08/10/2023 4:21:21 PM
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08/10/2023 4:21:21 PM
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
08/10/2023 4:21:21 PM
    rv = self.dispatch_request()
08/10/2023 4:21:21 PM
         ^^^^^^^^^^^^^^^^^^^^^^^
08/10/2023 4:21:21 PM
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
08/10/2023 4:21:21 PM
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
08/10/2023 4:21:21 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08/10/2023 4:21:21 PM
  File "/whoogle/app/routes.py", line 122, in decorated
08/10/2023 4:21:21 PM
    return f(*args, **kwargs)
08/10/2023 4:21:21 PM
           ^^^^^^^^^^^^^^^^^^
08/10/2023 4:21:21 PM
  File "/whoogle/app/routes.py", line 57, in decorated
08/10/2023 4:21:21 PM
    return f(*args, **kwargs)
08/10/2023 4:21:21 PM
           ^^^^^^^^^^^^^^^^^^
08/10/2023 4:21:21 PM
  File "/whoogle/app/routes.py", line 314, in search
08/10/2023 4:21:21 PM
    response = search_util.generate_response()
08/10/2023 4:21:21 PM
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08/10/2023 4:21:21 PM
  File "/whoogle/app/utils/search.py", line 165, in generate_response
08/10/2023 4:21:21 PM
    formatted_results = content_filter.clean(html_soup)
08/10/2023 4:21:21 PM
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08/10/2023 4:21:21 PM
  File "/whoogle/app/filter.py", line 170, in clean
08/10/2023 4:21:21 PM
    self.update_link(link)
08/10/2023 4:21:21 PM
    ^^^^^^^^^^^^^^^^^^^^^^
08/10/2023 4:21:21 PM
  File "/whoogle/app/filter.py", line 496, in update_link
08/10/2023 4:21:21 PM
    q = extract_q(result_link.query, href)
08/10/2023 4:21:21 PM
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08/10/2023 4:21:21 PM
  File "/whoogle/app/filter.py", line 47, in extract_q
08/10/2023 4:21:21 PM
    return parse_qs(q_str)['q'][0] if ('&q=' in href or '?q=' in href) else ''
08/10/2023 4:21:21 PM
           ~~~~~~~~~~~~~~~^^^^^
08/10/2023 4:21:21 PM
KeyError: 'q'
```

**Comment by ahmad-alkadri** [comment]
Confirmed getting the same bug on my docker instance.

It seems that the problem's coming from the parsing of the query. Curious if there's other instances of search queries producing this bug.
