### ISSUE TITLE
[BUG]  Internal server error (500) 

### ISSUE THREAD

**Issue by fr4gtp** [benbusby/whoogle-search#1117]
**Describe the bug**
open it in a browser, type anything into the search bar, and get Internal server error (500) 

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ x] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [Debian (DietPi, armv7)]
 - Browser [anyone]

**Additional context**

```shell 
Feb 15 10:27:57 korobok systemd[1]: Started whoogle.service - Whoogle.
Feb 15 10:28:00 korobok whoogle[11560]:  * Serving Flask app 'app'
Feb 15 10:28:00 korobok whoogle[11560]:  * Debug mode: on
Feb 15 10:28:00 korobok whoogle[11560]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
Feb 15 10:28:00 korobok whoogle[11560]:  * Running on all addresses (0.0.0.0)
Feb 15 10:28:00 korobok whoogle[11560]:  * Running on http://127.0.0.1:5000
Feb 15 10:28:00 korobok whoogle[11560]:  * Running on http://192.168.1.111:5000
Feb 15 10:28:00 korobok whoogle[11560]: Press CTRL+C to quit
Feb 15 10:28:00 korobok whoogle[11560]:  * Restarting with stat
Feb 15 10:28:03 korobok whoogle[11565]:  * Debugger is active!
Feb 15 10:28:03 korobok whoogle[11565]:  * Debugger PIN: 973-082-184
Feb 15 10:28:12 korobok whoogle[11565]: 192.168.1.201 - - [15/Feb/2024 10:28:12] "GET / HTTP/1.1" 200 -
Feb 15 10:28:13 korobok whoogle[11565]: 192.168.1.201 - - [15/Feb/2024 10:28:13] "GET /static/build/logo.72c3bd56.css HTTP/1.1" 304 -
Feb 15 10:28:13 korobok whoogle[11565]: 192.168.1.201 - - [15/Feb/2024 10:28:13] "GET /static/img/favicon/favicon-32x32.png HTTP/1.1" 304 -
Feb 15 10:28:16 korobok whoogle[11565]: 192.168.1.201 - - [15/Feb/2024 10:28:16] "POST /autocomplete HTTP/1.1" 200 -
Feb 15 10:28:16 korobok whoogle[11565]: 192.168.1.201 - - [15/Feb/2024 10:28:16] "POST /autocomplete HTTP/1.1" 200 -
Feb 15 10:28:17 korobok whoogle[11565]: 192.168.1.201 - - [15/Feb/2024 10:28:17] "POST /autocomplete HTTP/1.1" 200 -
Feb 15 10:28:17 korobok whoogle[11565]: 192.168.1.201 - - [15/Feb/2024 10:28:17] "POST /autocomplete HTTP/1.1" 200 -
Feb 15 10:28:17 korobok whoogle[11565]: 192.168.1.201 - - [15/Feb/2024 10:28:17] "POST /search HTTP/1.1" 500 -
Feb 15 10:28:17 korobok whoogle[11565]: 192.168.1.201 - - [15/Feb/2024 10:28:17] "GET /static/build/error.3d20eccf.css HTTP/1.1" 304 -
Feb 15 10:28:18 korobok whoogle[11565]: 192.168.1.201 - - [15/Feb/2024 10:28:18] "GET /favicon.ico HTTP/1.1" 500 -
Feb 15 10:28:18 korobok whoogle[11565]: Traceback (most recent call last):
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1484, in full_dispatch_request
Feb 15 10:28:18 korobok whoogle[11565]:     rv = self.dispatch_request()
Feb 15 10:28:18 korobok whoogle[11565]:          ^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1458, in dispatch_request
Feb 15 10:28:18 korobok whoogle[11565]:     self.raise_routing_exception(req)
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1440, in raise_routing_exception
Feb 15 10:28:18 korobok whoogle[11565]:     raise request.routing_exception  # type: ignore
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/flask/ctx.py", line 353, in match_request
Feb 15 10:28:18 korobok whoogle[11565]:     result = self.url_adapter.match(return_rule=True)  # type: ignore
Feb 15 10:28:18 korobok whoogle[11565]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/werkzeug/routing/map.py", line 624, in match
Feb 15 10:28:18 korobok whoogle[11565]:     raise NotFound() from None
Feb 15 10:28:18 korobok whoogle[11565]: werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Feb 15 10:28:18 korobok whoogle[11565]: During handling of the above exception, another exception occurred:
Feb 15 10:28:18 korobok whoogle[11565]: Traceback (most recent call last):
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 2213, in __call__
Feb 15 10:28:18 korobok whoogle[11565]:     return self.wsgi_app(environ, start_response)
Feb 15 10:28:18 korobok whoogle[11565]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
Feb 15 10:28:18 korobok whoogle[11565]:     return self.app(environ, start_response)
Feb 15 10:28:18 korobok whoogle[11565]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 2193, in wsgi_app
Feb 15 10:28:18 korobok whoogle[11565]:     response = self.handle_exception(e)
Feb 15 10:28:18 korobok whoogle[11565]:                ^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 2190, in wsgi_app
Feb 15 10:28:18 korobok whoogle[11565]:     response = self.full_dispatch_request()
Feb 15 10:28:18 korobok whoogle[11565]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1486, in full_dispatch_request
Feb 15 10:28:18 korobok whoogle[11565]:     rv = self.handle_user_exception(e)
Feb 15 10:28:18 korobok whoogle[11565]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1341, in handle_user_exception
Feb 15 10:28:18 korobok whoogle[11565]:     return self.handle_http_exception(e)
Feb 15 10:28:18 korobok whoogle[11565]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1281, in handle_http_exception
Feb 15 10:28:18 korobok whoogle[11565]:     return self.ensure_sync(handler)(e)
Feb 15 10:28:18 korobok whoogle[11565]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]:   File "/opt/whoogle-search/app/routes.py", line 609, in page_not_found
Feb 15 10:28:18 korobok whoogle[11565]:     return render_template('error.html', error_message=str(e)), 404
Feb 15 10:28:18 korobok whoogle[11565]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/flask/templating.py", line 151, in render_template
Feb 15 10:28:18 korobok whoogle[11565]:     return _render(app, template, context)
Feb 15 10:28:18 korobok whoogle[11565]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/flask/templating.py", line 132, in _render
Feb 15 10:28:18 korobok whoogle[11565]:     rv = template.render(context)
Feb 15 10:28:18 korobok whoogle[11565]:          ^^^^^^^^^^^^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 1301, in render
Feb 15 10:28:18 korobok whoogle[11565]:     self.environment.handle_exception()
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 936, in handle_exception
Feb 15 10:28:18 korobok whoogle[11565]:     raise rewrite_traceback_stack(source=source)
Feb 15 10:28:18 korobok whoogle[11565]:   File "/opt/whoogle-search/app/templates/error.html", line 23, in top-level template code
Feb 15 10:28:18 korobok whoogle[11565]:     <h4><a class="link" href="https://farside.link">{{ translation['continue-search'] }}</a></h4>
Feb 15 10:28:18 korobok whoogle[11565]:   File "/usr/local/lib/python3.11/dist-packages/jinja2/environment.py", line 466, in getitem
Feb 15 10:28:18 korobok whoogle[11565]:     return obj[argument]
Feb 15 10:28:18 korobok whoogle[11565]:            ^^^^^^^^^^^^^
Feb 15 10:28:18 korobok whoogle[11565]: jinja2.exceptions.UndefinedError: 'translation' is undefined
```

**Comment by benbusby** [comment]
This should be fixed with ef54f0021267d039f7444d709296c627882d4495
