### ISSUE TITLE
[BUG] Python 3.13 support?

### ISSUE THREAD

**Issue by dr460nf1r3** [benbusby/whoogle-search#1207]
**Describe the bug**
Python 3.13 has arrived in Arch repositories, and seemingly it broke Whoogle. There is a loop of the following logs after building it:

~~~
Dec 25 09:38:07 dragons-ryzen whoogle[37663]: ModuleNotFoundError: No module named 'cgi'
Dec 25 09:38:10 dragons-ryzen whoogle[37665]: Traceback (most recent call last):
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "/opt/whoogle-search/venv/lib/python3.13/site-packages/cssutils/util.py", line 16, in <module>
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:     from ._fetchgae import _defaultFetcher
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "/opt/whoogle-search/venv/lib/python3.13/site-packages/cssutils/_fetchgae.py", line 5, in <module>
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:     from google.appengine.api import urlfetch
Dec 25 09:38:10 dragons-ryzen whoogle[37665]: ModuleNotFoundError: No module named 'google'
Dec 25 09:38:10 dragons-ryzen whoogle[37665]: During handling of the above exception, another exception occurred:
Dec 25 09:38:10 dragons-ryzen whoogle[37665]: Traceback (most recent call last):
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "<frozen runpy>", line 189, in _run_module_as_main
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "<frozen runpy>", line 148, in _get_module_details
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "<frozen runpy>", line 112, in _get_module_details
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "/opt/whoogle-search/app/__init__.py", line 1, in <module>
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:     from app.filter import clean_query
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "/opt/whoogle-search/app/filter.py", line 1, in <module>
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:     import cssutils
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "/opt/whoogle-search/venv/lib/python3.13/site-packages/cssutils/__init__.py", line 80, in <module>
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:     from . import css
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "/opt/whoogle-search/venv/lib/python3.13/site-packages/cssutils/css/__init__.py", line 60, in <module>
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:     from .cssstylesheet import CSSStyleSheet
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "/opt/whoogle-search/venv/lib/python3.13/site-packages/cssutils/css/cssstylesheet.py", line 13, in <module>
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:     from cssutils.util import _Namespaces, _readUrl
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "/opt/whoogle-search/venv/lib/python3.13/site-packages/cssutils/util.py", line 18, in <module>
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:     from ._fetch import _defaultFetcher
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "/opt/whoogle-search/venv/lib/python3.13/site-packages/cssutils/_fetch.py", line 12, in <module>
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:     import encutils
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:   File "/opt/whoogle-search/venv/lib/python3.13/site-packages/encutils/__init__.py", line 55, in <module>
Dec 25 09:38:10 dragons-ryzen whoogle[37665]:     import cgi
Dec 25 09:38:10 dragons-ryzen whoogle[37665]: ModuleNotFoundError: No module named 'cgi'

~~~

**To Reproduce**
1. Use either method to obtain a fully updated Arch system (e.g. Docker or Distrobox)
2. Build the app as outlined (I used the [AUR PKGBUILD](https://aur.archlinux.org/packages/whoogle-git)
3. Start the app

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: Archlinux + PKGBUILD linked above (which uses the Systemd method of the README)

**Version of Whoogle Search**
- [x] Latest build from [source] latest master branch commit via 
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Archlinux

**Other information**

From a quick search, it looks like `cgi` no longer exists in Python 3.13? 

https://github.com/rpetit3/fastq-dl/issues/34
https://github.com/cherrypy/cherrypy/issues/2014#issue-2067137907

**Comment by pezz** [comment]
Yeah, same here, broken after the 3.13 upgrade. I thought installing python-cgi then rebuilding might fix it, but nah.

**Comment by TheRolfFR** [comment]
Project is using 2022 version of cssutils. According to what I read on this news document, on this paragraph https://github.com/jaraco/cssutils/blob/main/NEWS.rst#v270, 2.7.0 updated deprecated the use of cgi module. Try upgrading to `cssutils==2.7.0` into the [requirements.txt](https://github.com/benbusby/whoogle-search/blob/e70bbabd63408c6a5ba6d99953f604e3d57d78f9/requirements.txt#L11C1-L11C9) and retry

**Comment by pezz** [comment]
Got around to trying this, confirmed that updating requirements.txt with `cssutils==2.7.0` fixes it.

**Comment by pezz** [comment]
@benbusby  Any chance you could bump the version of cssutils in requirements.txt? 2.7.0 seems to work.

**Comment by pezz** [comment]
True, but I'd probably screw it up. :)
