### ISSUE TITLE
[BUG] Search engine seemingly random not responding to search queries

### ISSUE THREAD

**Issue by dr460nf1r3** [benbusby/whoogle-search#188]
**Describe the bug**
Whoogle wouldnt seemingly not give search results for some time. The page loads correctly, search query is entered afterwards and the search started. Here the browser starts loading the new page but never finishes (without error message or anything). After a few hours it works again. 
I had a look at the docker logs and found this messages being spammed:
```
INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0003)
INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0004)
INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"
DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0003)
INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0003)
INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"
DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0003)
INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
INFO:stem:Error while receiving a control message (SocketClosed): received exception "peek of closed file"
DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0003)
INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"
DEBUG:stem:GETCONF __owningcontrollerprocess (runtime: 0.0003)
INFO:stem:Error while receiving a control message (SocketClosed): received exception "read of closed file"
```

**To Reproduce**
Cant reproduce probably. 

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Garuda Linux (Arch)
 - Browser [e.g. chrome, safari] Ungoogled Chromium
 - Version [e.g. 22] 88

**Additional context**

**Comment by linuxtopia** [comment]
Same thing occurs on my usage for every Whoogle instances from other servers too, tried all and same results.

Every applied or saved configurations been changed by automation after a while and this makes me sick!

**Comment by arankaren** [comment]
Logs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/whoogle/app/routes.py", line 38, in decorated
    return f(*args, **kwargs)
  File "/whoogle/app/routes.py", line 227, in search
    session['config']['tor'] = False if e.disable else session['config'][
KeyError: 'tor'
Aug 02 02:51:37.000 [notice] New control connection opened from 127.0.0.1.
Aug 02 02:51:37.000 [notice] Heartbeat: Tor's uptime is 0:01 hours, with 9 circuits open. I've sent 558 kB and received 4.07 MB.
```
