### ISSUE TITLE
[BUG] 0.5.1 breaks some searches

### ISSUE THREAD

**Issue by mrckndt** [benbusby/whoogle-search#334]
**Describe the bug**
Only some searches ("libera drop account" e.g. `http://localhost:5000/search?q=libera+drop+account`) leads to an internal server error:
```
whoogle   | ERROR:app:Exception on /search [GET]
whoogle   | Traceback (most recent call last):
whoogle   |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
whoogle   |     response = self.full_dispatch_request()
whoogle   |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
whoogle   |     rv = self.handle_user_exception(e)
whoogle   |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
whoogle   |     reraise(exc_type, exc_value, tb)
whoogle   |   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
whoogle   |     raise value
whoogle   |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
whoogle   |     rv = self.dispatch_request()
whoogle   |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
whoogle   |     return self.view_functions[rule.endpoint](**req.view_args)
whoogle   |   File "/whoogle/app/routes.py", line 39, in decorated
whoogle   |     return f(*args, **kwargs)
whoogle   |   File "/whoogle/app/routes.py", line 223, in search
whoogle   |     response = search_util.generate_response()
whoogle   |   File "/whoogle/app/utils/search.py", line 150, in generate_response
whoogle   |     formatted_results = content_filter.clean(html_soup)
whoogle   |   File "/whoogle/app/filter.py", line 81, in clean
whoogle   |     self.update_link(link)
whoogle   |   File "/whoogle/app/filter.py", line 226, in update_link
whoogle   |     query = parse_qs(
whoogle   | KeyError: 'q'
whoogle   | May 28 23:42:26.000 [notice] New control connection opened from 127.0.0.1.
whoogle   | May 28 23:42:26.000 [notice] Heartbeat: Tor's uptime is 0:02 hours, with 10 circuits open. I've sent 414 kB and received 2.72 MB.
whoogle   | WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - Firefox 88 and Chromium 90
 
**Smartphone (please complete the following information):**
- Android 11
- Firefox 88

**Additional context**
In 0.5.0 the example search works just fine.

**Comment by benbusby** [comment]
Thanks for bringing this to my attention! I've pushed a fix with cbe32a081eff36640b0c0e3b5e68b62e59f06fcd, which has been included in a new 0.5.2 release.
