### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by pranjal-b** [benbusby/whoogle-search#371]
whoogle-search-main>whoogle-search
Traceback (most recent call last):
  File "c:\users\pranj\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\pranj\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pranj\AppData\Local\Programs\Python\Python37\Scripts\whoogle-search.exe\__main__.py", line 4, in <module>
  File "c:\users\pranj\appdata\local\programs\python\python37\lib\site-packages\app\__init__.py", line 34, in <module>
    os.path.join(app.config['STATIC_FOLDER'], 'settings/languages.json')))
  File "c:\users\pranj\appdata\local\programs\python\python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\users\pranj\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 289: character maps to <undefined>

**Comment by Vinyzu** [comment]
same error ^^
