### ISSUE TITLE
Docker-compose deployment error when running container: PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by jzt308** [benbusby/whoogle-search#375]
Hi all, 
this morning i noticed that my private whoogle deployment stopped. I didn't change anything and am running the latest version (see compose file). I tried to run it on a different server (Debian stable with latest docker and docker-compose installed) where no previous images where deployed but no joy. Same error. I tried disabling the tmpfs section in my compose file but this makes no difference.
Before posting I searched for this issue but had no luck finding it so I'm hoping you can help.

OS: Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
Docker-compose: docker-compose version 1.29.2, build 5becea4c
Docker: Server: Docker Engine - Community
Engine:  Version:          20.10.7

Error:
today at 11:18  Jul 11 09:18:13.777 [notice] Tor 0.3.5.15 running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
today at 11:18  Jul 11 09:18:13.777 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
today at 11:18  Jul 11 09:18:13.777 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
today at 11:18  Jul 11 09:18:13.777 [notice] Read configuration file "/etc/tor/torrc".
today at 11:18  Jul 11 09:18:13.789 [warn] Error setting groups to gid 102: "Operation not permitted".
today at 11:18  Jul 11 09:18:13.789 [warn] If you set the "User" option, you must start Tor as root.
today at 11:18  Jul 11 09:18:13.789 [warn] Failed to parse/validate config: Problem with User value. See logs for details.
today at 11:18  Jul 11 09:18:13.789 [err] Reading config failed--see warnings above.
today at 11:18  Traceback (most recent call last):
today at 11:18    File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
today at 11:18      mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
today at 11:18    File "/usr/local/lib/python3.8/runpy.py", line 144, in _get_module_details
today at 11:18      return _get_module_details(pkg_main_name, error)
today at 11:18    File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
today at 11:18      __import__(pkg_name)
today at 11:18    File "/whoogle/app/__init__.py", line 84, in <module>
today at 11:18      os.makedirs(app.config['SESSION_FILE_DIR'])
today at 11:18    File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
today at 11:18      mkdir(name, mode)
today at 11:18  PermissionError: [Errno 13] Permission denied: '/config/session'

Docker-compose:
version: '3.8'

services:
  whoogle-search:
    image: benbusby/whoogle-search
    container_name: whoogle-search
    restart: unless-stopped

    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    read_only: true

    ports:
      - 5000:5000

    tmpfs:
      - /config/:size=10M,uid=102,gid=102,mode=1700
      - /var/lib/tor/:size=10M,uid=102,gid=102,mode=1700
      - /run/tor/:size=1M,uid=102,gid=102,mode=1700

**Comment by bruvv** [comment]
make sure the PGUD and PUID have the correct write permission for `/config/`

**Comment by jzt308** [comment]
Maybe I don't understand. I am not specifying a PUID or PGID in the docker-compose and am running the process under root. There are no volume mappings so where do I need to specify them? (Strange thing is it was working and I didn't change a thing).

**Comment by asitemade4u** [comment]
I have the exact same issue. Shall I create user with userid = 102 on the host machine?

**Comment by Painkiller16** [comment]
I also have same issue on debian 10 with portainer template, how can repair issue??

**Comment by Albonycal** [comment]
-  If you are using docker-compose this release will break your instance
   unless you update your docker-compose.yml with the latest changes:
   -
   https://github.com/benbusby/whoogle-search/blob/1af4566991f5248fd0d3576ca4fbcc0a84293004/docker-compose.yml#L14
   -
   https://github.com/benbusby/whoogle-search/blob/1af4566991f5248fd0d3576ca4fbcc0a84293004/docker-compose.yml#L19-L22

**Comment by asitemade4u** [comment]
It worked, Thanks!

**Comment by Albonycal** [comment]
😀
