### ISSUE TITLE
[BUG] Search not working 

### ISSUE THREAD

**Issue by Mazawrath** [benbusby/whoogle-search#577]
**Describe the bug**
Searching anything doesn't work

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [x] Other: Digital Ocean

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version [version number]
- [ ] Not sure

**Additional context**
This only started happening after updating to v0.7.0
```[whoogle] [2021-12-13 19:02:51] WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[whoogle] [2021-12-13 19:06:06] WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[whoogle] [2021-12-13 19:09:36] WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[whoogle] [2021-12-13 19:12:47] WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[whoogle] [2021-12-13 19:16:22] WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[whoogle] [2021-12-13 19:16:30] ERROR:app:Exception on /element [GET]
[whoogle] [2021-12-13 19:16:30] Traceback (most recent call last):
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/cryptography/fernet.py", line 113, in _verify_signature
[whoogle] [2021-12-13 19:16:30]     h.verify(data[-32:])
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/primitives/hmac.py", line 70, in verify
[whoogle] [2021-12-13 19:16:30]     ctx.verify(signature)
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 76, in verify
[whoogle] [2021-12-13 19:16:30]     raise InvalidSignature("Signature did not match digest.")
[whoogle] [2021-12-13 19:16:30] cryptography.exceptions.InvalidSignature: Signature did not match digest.
[whoogle] [2021-12-13 19:16:30] 
[whoogle] [2021-12-13 19:16:30] During handling of the above exception, another exception occurred:
[whoogle] [2021-12-13 19:16:30] 
[whoogle] [2021-12-13 19:16:30] Traceback (most recent call last):
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
[whoogle] [2021-12-13 19:16:30]     response = self.full_dispatch_request()
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
[whoogle] [2021-12-13 19:16:30]     rv = self.handle_user_exception(e)
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
[whoogle] [2021-12-13 19:16:30]     reraise(exc_type, exc_value, tb)
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
[whoogle] [2021-12-13 19:16:30]     raise value
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
[whoogle] [2021-12-13 19:16:30]     rv = self.dispatch_request()
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
[whoogle] [2021-12-13 19:16:30]     return self.view_functions[rule.endpoint](**req.view_args)
[whoogle] [2021-12-13 19:16:30]   File "/whoogle/app/routes.py", line 90, in decorated
[whoogle] [2021-12-13 19:16:30]     return f(*args, **kwargs)
[whoogle] [2021-12-13 19:16:30]   File "/whoogle/app/routes.py", line 53, in decorated
[whoogle] [2021-12-13 19:16:30]     return f(*args, **kwargs)
[whoogle] [2021-12-13 19:16:30]   File "/whoogle/app/routes.py", line 433, in element
[whoogle] [2021-12-13 19:16:30]     src_url = cipher_suite.decrypt(request.args.get('url').encode()).decode()
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/cryptography/fernet.py", line 76, in decrypt
[whoogle] [2021-12-13 19:16:30]     return self._decrypt_data(data, timestamp, ttl, int(time.time()))
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/cryptography/fernet.py", line 125, in _decrypt_data
[whoogle] [2021-12-13 19:16:30]     self._verify_signature(data)
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/cryptography/fernet.py", line 115, in _verify_signature
[whoogle] [2021-12-13 19:16:30]     raise InvalidToken
[whoogle] [2021-12-13 19:16:30] cryptography.fernet.InvalidToken
[whoogle] [2021-12-13 19:16:30] ERROR:app:Exception on /search [GET]
[whoogle] [2021-12-13 19:16:30] Traceback (most recent call last):
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
[whoogle] [2021-12-13 19:16:30]     response = self.full_dispatch_request()
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
[whoogle] [2021-12-13 19:16:30]     rv = self.handle_user_exception(e)
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
[whoogle] [2021-12-13 19:16:30]     reraise(exc_type, exc_value, tb)
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
[whoogle] [2021-12-13 19:16:30]     raise value
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
[whoogle] [2021-12-13 19:16:30]     rv = self.dispatch_request()
[whoogle] [2021-12-13 19:16:30]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
[whoogle] [2021-12-13 19:16:30]     return self.view_functions[rule.endpoint](**req.view_args)
[whoogle] [2021-12-13 19:16:30]   File "/whoogle/app/routes.py", line 88, in decorated
[whoogle] [2021-12-13 19:16:30]     os.remove(invalid_session)
[whoogle] [2021-12-13 19:16:30] FileNotFoundError: [Errno 2] No such file or directory: '/config/session/2029240f6d1128be89ddc32729463129'
[whoogle] [2021-12-13 19:19:43] WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[whoogle] [2021-12-13 19:20:12] ERROR:app:Exception on /search [POST]
[whoogle] [2021-12-13 19:20:12] Traceback (most recent call last):
[whoogle] [2021-12-13 19:20:12]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
[whoogle] [2021-12-13 19:20:12]     response = self.full_dispatch_request()
[whoogle] [2021-12-13 19:20:12]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
[whoogle] [2021-12-13 19:20:12]     rv = self.handle_user_exception(e)
[whoogle] [2021-12-13 19:20:12]   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
[whoogle] [2021-12-13 19:20:12]     reraise(exc_type, exc_value, tb)
[whoogle] [2021-12-13 19:20:12]   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
[whoogle] [2021-12-13 19:20:12]     raise value```

**Comment by Mazawrath** [comment]
As a side note the webpage when I try to search isn't helpful either.
![image](https://user-images.githubusercontent.com/18429276/145882764-15db08c4-b880-4ee6-a92d-9b4634bd69dc.png)

**Comment by Mazawrath** [comment]
Downgrading back to v0.6.0 didn't work either. This might be an issue with my end but I'm not sure what caused this.

**Comment by bruvv** [comment]
Getting the same erros out of the blue with v0.7.0
I redid everything. Weird error that `/config/session/` folder now found...

**Comment by DUOLabs333** [comment]
Can you try going from source directly?

**Comment by Mazawrath** [comment]
I'm wondering if it's Digital Ocean.
Completely wiping the entire app and starting fresh on v0.7.0 caused the same exact thing. Works for the first few minutes and then refuses to do any searches.

**Comment by glitsj16** [comment]
> [whoogle] [2021-12-13 19:16:30] FileNotFoundError: [Errno 2] No such file or directory: '/config/session/2029240f6d1128be89ddc32729463129'

I've seen this too (on a Digital Ocean droplet running Arch Linux with Python 3.10). It went away after stopping the service, purging `app/static/config/session` and restarting whoogle-search (latest git master install). Has been running for about 20 hours now without hickups.

**Comment by lightningquick** [comment]
Has this issue been solved? if so  how do I fix this. 
Thanks. I dont run a digital ocean device. Whoogle broken is just too damn hard. I cant use any of my devices...
