### ISSUE TITLE
[BUG] Installation fails when using "D) Manual" on Linux Mint 19.3 Cinnamon

### ISSUE THREAD

**Issue by mendel5** [benbusby/whoogle-search#58]
My system is running on Linux Mint 19.3 Cinnamon. I would like to install Whoogle using the method "D) Manual" as described in the README.md.

These steps have worked:
```
git clone https://github.com/benbusby/whoogle-search.git
cd whoogle-search
python3 -m venv venv
source venv/bin/activate
```

But when I run the next step `pip install -r requirements.txt` I get this error:
```
$ pip install -r requirements.txt 
Collecting beautifulsoup4==4.8.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cb/a1/c698cf319e9cfed6b17376281bd0efc6bfc8465698f54170ef60a485ab5d/beautifulsoup4-4.8.2-py3-none-any.whl (106kB)
    100% |████████████████████████████████| 112kB 1.9MB/s 
Collecting bs4==0.0.1 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Collecting cffi==1.13.2 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/49/72/0d42f94fe94afa8030350c26e9d787219f3f008ec9bf6b86c66532b29236/cffi-1.13.2-cp36-cp36m-manylinux1_x86_64.whl (397kB)
    100% |████████████████████████████████| 399kB 2.4MB/s 
Collecting Click==7.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 4.5MB/s 
Collecting cryptography==2.8 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/45/73/d18a8884de8bffdcda475728008b5b13be7fbef40a2acc81a0d5d524175d/cryptography-2.8-cp34-abi3-manylinux1_x86_64.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 763kB/s 
Collecting Flask==1.1.1 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94kB)
    100% |████████████████████████████████| 102kB 7.4MB/s 
Collecting itsdangerous==1.1.0 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting Jinja2==2.10.3 (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 5.4MB/s 
Collecting MarkupSafe==1.1.1 (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser==2.19 (from -r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 6.4MB/s 
Collecting pycurl==7.43.0.4 (from -r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/0f/52/2c6951c4cd8a4e9288f2561eb9da1dc15b5d0f4e610a7e2acf39bc703281/pycurl-7.43.0.4.tar.gz (215kB)
    100% |████████████████████████████████| 225kB 4.7MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-s8wym11l/pycurl/setup.py", line 234, in configure_unix
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-s8wym11l/pycurl/setup.py", line 957, in <module>
        ext = get_extension(sys.argv, split_extension_source=split_extension_source)
      File "/tmp/pip-build-s8wym11l/pycurl/setup.py", line 618, in get_extension
        ext_config = ExtensionConfiguration(argv)
      File "/tmp/pip-build-s8wym11l/pycurl/setup.py", line 101, in __init__
        self.configure()
      File "/tmp/pip-build-s8wym11l/pycurl/setup.py", line 238, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'
```

Can you help me?

**Comment by mendel5** [comment]
Found the mistake: I did not install the dependencies when starting with the installation.

In the README.md it currently says:
"If using Heroku Quick Deploy, **you can skip this section.**"

I read a little bit too fast and skipped the section even though I was not using Heroku Quick Deploy...

This fixed it:
`sudo apt-get install -y libcurl4-openssl-dev libssl-dev`

**Comment by mendel5** [comment]
In the meantime I got a new error about `bdist_wheel` and `Python.h`:
1. `error: invalid command 'bdist_wheel'`
2. `src/pycurl.h:5:10: fatal error: Python.h: No such file or directory`

Fixes:
1. https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci
2. https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by mendel5** [comment]
Now it works!
