### ISSUE TITLE
[BUG] UnicodeDecodeError

### ISSUE THREAD

**Issue by mogh-k** [benbusby/whoogle-search#581]
After installing whoogle with pip, and trying to run `whoogle-search --help`, I keep getting this:
```
Traceback (most recent call last):
  File "c:\users\moghk\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\moghk\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\moghk\AppData\Local\Programs\Python\Python39\Scripts\whoogle-search.exe\__main__.py", line 4, in <module>
  File "c:\users\moghe\appdata\local\programs\python\python39\lib\site-packages\app\__init__.py", line 47, in <module>
    app.config['TRANSLATIONS'] = json.load(open(
  File "c:\users\moghk\appdata\local\programs\python\python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\users\moghk\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 10756: character maps to <undefined>
```
Whenever I type in any `whoogle-search` command it returns with that. What is happening and how can I fix it?

**Comment by DUOLabs333** [comment]
It seems that for Windows, for some reason, encoded the json file with `CP1252`, instead of `UTF-8`. Shouldn't happen though.
