### ISSUE TITLE
[BUG] xml.etree.ElementTree.ParseError: not well-formed (invalid token)

### ISSUE THREAD

**Issue by bruvv** [benbusby/whoogle-search#593]
**Describe the bug**
```
ERROR:app:Exception on /autocomplete [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/whoogle/app/routes.py", line 275, in autocomplete
    g.user_request.autocomplete(q) if not g.user_config.tor else []
  File "/whoogle/app/request.py", line 232, in autocomplete
    root = ET.fromstring(response)
  File "/usr/local/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 2, column 11
```

![afbeelding](https://user-images.githubusercontent.com/3063928/147465690-19af0298-f6ba-4b7b-af82-3ed50fb8710b.png)

**To Reproduce**
1. install latest tag using docker
2. use it and out of the blue it will shown an error

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [X] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [X] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows 10, Mac, Android etc
 - Browser: Chrome, firefox, safari
 - Version: Different versions

**Additional context**

**Comment by benbusby** [comment]
Thanks for reporting!
