### ISSUE TITLE
[BUG] Error when deploying to Raspberry Pi 400 using Docker

### ISSUE THREAD

**Issue by Im-Kal** [benbusby/whoogle-search#702]
**Describe the bug**
Hello,
I have got my hands on a Raspberry Pi 400 and tried installed Whoogle with docker using ```docker pull benbusby/whoogle-search:latest``` but it would return a error stating that there is too many levels of symbolic links.
I tried cloning the repo and have successfully done so, but when I run ```docker-compose up``` I get the following errors. I have updated my rPI and have checked all issues using Search.

**To Reproduce**
1. ```git clone https://github.com/benbusby/whoogle-search.git```
2. ```cd whoogle-search/```
3. ```docker-compose up```
4. Traceback (most recent call last):
  File "/home/pi/.local/bin/docker-compose", line 6, in <module>
    from compose.cli.main import main
  File "/home/pi/.local/lib/python2.7/site-packages/compose/cli/main.py", line 18, in <module>
    import docker.errors
  File "/home/pi/.local/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/home/pi/.local/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/home/pi/.local/lib/python2.7/site-packages/docker/api/client.py", line 10, in <module>
    from .. import auth
  File "/home/pi/.local/lib/python2.7/site-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/home/pi/.local/lib/python2.7/site-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/home/pi/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/home/pi/.local/lib/python2.7/site-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/home/pi/.local/lib/python2.7/site-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/home/pi/.local/lib/python2.7/site-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/home/pi/.local/lib/python2.7/site-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [x] Docker
- [ ] `run` executable
- [ ] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [x] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [ ] Version [version number]
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster) armv71

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Im-Kal** [comment]
@benbusby Please help in this issue.

**Comment by benbusby** [comment]
@Im-Kal I don't have a spare Pi to investigate this issue, but from a quick search, it seems to be a somewhat common problem with Python2.7 + Docker on Debian based systems in particular.

Here are some things I found from just searching your error, feel free to try some:

- https://stackoverflow.com/questions/42695004/importerror-no-module-named-ssl-match-hostname-when-importing-the-docker-sdk-fo
- https://github.com/docker/docker-py/issues/1502#issuecomment-576720696
- https://github.com/docker/docker-py/issues/1502#issuecomment-418346541
- https://github.com/docker/docker-py/issues/1502#issuecomment-509898861

Seems like there's more help online for fixing the issue if you look around. This doesn't seem to be a bug with Whoogle necessarily, but rather a device configuration issue.

**Comment by Im-Kal** [comment]
Thanks a lot, you literally saved my life
