### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by nobicycle** [benbusby/whoogle-search#777]
**Describe the bug**
```
MemoryError
MemoryError

Traceback (most recent call last)
File "/home/user/Development/Python/whoogle-search/lib/python3.10/site-packages/flask/app.py", line 2095, in __call__
return self.wsgi_app(environ, start_response)
File "/home/user/Development/Python/whoogle-search/lib/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
return self.app(environ, start_response)
File "/home/user/Development/Python/whoogle-search/lib/python3.10/site-packages/flask/app.py", line 2080, in wsgi_app
response = self.handle_exception(e)
File "/home/user/Development/Python/whoogle-search/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
response = self.full_dispatch_request()
File "/home/user/Development/Python/whoogle-search/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/user/Development/Python/whoogle-search/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
rv = self.dispatch_request()
File "/home/user/Development/Python/whoogle-search/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/user/Development/Python/whoogle-search/lib/python3.10/site-packages/app/routes.py", line 79, in decorated
_ = pickle.load(session_file)
MemoryError
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

```
**To Reproduce**
1. Start Server.'
2. Enter a search term in the browser (in my case '"food"

**Deployment Method**
pip/pipx

**Version of Whoogle Search**
v0.7.3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Manjaro Linux
 - Browser [e.g. chrome, safari] Vivaldi
 - Versionv5.2.2623.46 (Stable 

**Additional context**
$ python -V
Python 3.10.4

**Comment by DUOLabs333** [comment]
What's your config?

**Comment by nobicycle** [comment]
> What's your config?

None apart from a port change. I am using  vanilla pip install. In  systemd service (copied in full below) I use 
`python bin/whoogle-search --host 127.0.0.1 --port 8754`

The systemd service is reporting :

```
$ systemctl status whoogle
● whoogle.service - Whoogle
     Loaded: loaded (/usr/lib/systemd/system/whoogle.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2022-06-14 07:32:40 WITA; 14min ago
   Main PID: 102474 (python)
      Tasks: 5 (limit: 4511)
     Memory: 71.1M
        CPU: 1.575s
     CGroup: /system.slice/whoogle.service
             └─ 102474 python bin/whoogle-search --host 127.0.0.1 --port 8754

Jun 14 07:46:43 tower whoogle[102474]:   File "/home/user/Development/Python/whoogle-search/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
Jun 14 07:46:43 tower whoogle[102474]:     rv = self.handle_user_exception(e)
Jun 14 07:46:43 tower whoogle[102474]:   File "/home/user/Development/Python/whoogle-search/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
Jun 14 07:46:43 tower whoogle[102474]:     rv = self.dispatch_request()
Jun 14 07:46:43 tower whoogle[102474]:   File "/home/user/Development/Python/whoogle-search/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
Jun 14 07:46:43 tower whoogle[102474]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jun 14 07:46:43 tower whoogle[102474]:   File "/home/user/Development/Python/whoogle-search/lib/python3.10/site-packages/app/routes.py", line 79, in decorated
Jun 14 07:46:43 tower whoogle[102474]:     _ = pickle.load(session_file)
Jun 14 07:46:43 tower whoogle[102474]: MemoryError
Jun 14 07:46:44 tower whoogle[102474]: WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```



[Unit]
Description=Whoogle

[Service]
Type=simple
User=user
ExecStart=/bin/bash -c "cd '/home/user/Development/Python/whoogle-search' && . bin/activate && python bin/whoogle-search --host 127.0.0.1 --port 8754"
ExecReload=/bin/kill -HUP 
Restart=always
RestartSec=3
SyslogIdentifier=whoogle

[Install]
WantedBy=multi-user.target

**Comment by nobicycle** [comment]
I just upgraded to  v0.7.4 and have the same error.

**Comment by benbusby** [comment]
This should be fixed now, I'll try to release a new pip version soon. In the meantime you can use the [TestPyPi version](https://test.pypi.org/project/whoogle-search/0.7.4.dev1655401870/) of the package to validate the fix.

**Comment by nobicycle** [comment]
I noticed a later version.
https://test.pypi.org/project/whoogle-search/

Problem fixed.

Thank you.
