### ISSUE TITLE
[BUG] UnicodeDecodeError

### ISSUE THREAD

**Issue by bibimagic** [benbusby/whoogle-search#802]
When I run a search with whoogle, the following message appears in the web browser:
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

This is caused by the error:
```
ERROR:app:Exception on /search [POST]
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2446, in wsgi_app
  response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1951, in full_dispatch_request
  rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in handle_user_exception
  reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.10/dist-packages/flask/_compat.py", line 39, in reraise
  raise value
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python3.10/dist-packages/app/routes.py", line 79, in decorated
  _ = pickle.load(session_file)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9b in position 1: invalid start byte
```

Please tell me how I can solve this problem.

Installation on Ubuntu 22.04 with the "pip" method.

**Comment by bibimagic** [comment]
Problem solved by replacing the routes.py file of the "pip" installation by the "main branch" one.
