### ISSUE TITLE
[BUG] <brief bug description>

### ISSUE THREAD

**Issue by Sailing74** [benbusby/whoogle-search#816]
**Describe the bug**
Calling Whoogle leads to err 500 being shown in the browser.
log says:
`Jul 17 08:29:48 whoogle whoogle-search[120]: ERROR:app:Exception on /search [GET]
Jul 17 08:29:48 whoogle whoogle-search[120]: Traceback (most recent call last):
Jul 17 08:29:48 whoogle whoogle-search[120]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2077, in wsgi_app
Jul 17 08:29:48 whoogle whoogle-search[120]:     response = self.full_dispatch_request()
Jul 17 08:29:48 whoogle whoogle-search[120]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1525, in full_dispatch_request
Jul 17 08:29:48 whoogle whoogle-search[120]:     rv = self.handle_user_exception(e)
Jul 17 08:29:48 whoogle whoogle-search[120]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1523, in full_dispatch_request
Jul 17 08:29:48 whoogle whoogle-search[120]:     rv = self.dispatch_request()
Jul 17 08:29:48 whoogle whoogle-search[120]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1509, in dispatch_request
Jul 17 08:29:48 whoogle whoogle-search[120]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jul 17 08:29:48 whoogle whoogle-search[120]:   File "/usr/local/lib/python3.9/dist-packages/app/routes.py", line 79, in decorated
Jul 17 08:29:48 whoogle whoogle-search[120]:     _ = pickle.load(session_file)
Jul 17 08:29:48 whoogle whoogle-search[120]: ValueError: unregistered extension code 250
Jul 17 08:29:48 whoogle systemd-journald[52]: Forwarding to syslog missed 2 messages.
Jul 17 08:29:48 whoogle whoogle-search[120]: WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
`
**To Reproduce**
submit a search query to Whoogle using the formatted URL http://<whoogle>:5000/search?q=%s, e.g.:
http://192.168.1.201:5000/search?q=whoogle+error

**Deployment Method**
- [X] pip/pipx
- [X] Other: [describe setup]

`apt-get install -y curl
apt-get install -y sudo
apt-get install -y libcurl4-openssl-dev libssl-dev
apt-get install python3-pip -y
pip install whoogle-search`

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [X] Version 0.7.4 II
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Firefox, Vivaldi, Chrome, Edge

**Additional Information
After activating the debug log, I get the following:

`Jul 17 08:58:53 whoogle systemd[1]: Started Whoogle-Search.
Jul 17 08:58:53 whoogle whoogle-search[492]:  * Serving Flask app 'app' (lazy loading)
Jul 17 08:58:53 whoogle whoogle-search[492]:  * Environment: production
Jul 17 08:58:53 whoogle whoogle-search[492]:    WARNING: This is a development server. Do not use it in a production deployment.
Jul 17 08:58:53 whoogle whoogle-search[492]:    Use a production WSGI server instead.
Jul 17 08:58:53 whoogle whoogle-search[492]:  * Debug mode: on
Jul 17 08:58:53 whoogle whoogle-search[492]:  * Running on all addresses (0.0.0.0)
Jul 17 08:58:53 whoogle whoogle-search[492]:    WARNING: This is a development server. Do not use it in a production deployment.
Jul 17 08:58:53 whoogle whoogle-search[492]:  * Running on http://127.0.0.1:5000
Jul 17 08:58:53 whoogle whoogle-search[492]:  * Running on http://192.168.1.201:5000 (Press CTRL+C to quit)
Jul 17 08:58:53 whoogle whoogle-search[492]:  * Restarting with stat
Jul 17 08:58:54 whoogle whoogle-search[493]:  * Debugger is active!
Jul 17 08:58:54 whoogle whoogle-search[493]:  * Debugger PIN: 197-754-054
Jul 17 08:59:12 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:12] "GET / HTTP/1.1" 200 -
Jul 17 08:59:12 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:12] "GET /static/build/main.68be5054.css HTTP/1.1" 304 -
Jul 17 08:59:12 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:12] "GET /static/build/logo.72c3bd56.css HTTP/1.1" 304 -
Jul 17 08:59:12 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:12] "GET /static/build/autocomplete.1661f315.js HTTP/1.1" 304 -
Jul 17 08:59:12 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:12] "GET /static/build/controller.d5f7f262.js HTTP/1.1" 304 -
Jul 17 08:59:12 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:12] "GET /static/build/light-theme.7a8a8dcc.css HTTP/1.1" 304 -
Jul 17 08:59:12 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:12] "GET /static/build/dark-theme.73b9ead8.css HTTP/1.1" 304 -
Jul 17 08:59:15 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:15] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:15 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:15] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:16 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:16] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:16 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:16] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:16 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:16] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:17 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:17] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:17 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:17] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:17 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:17] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:17 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:17] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:17 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:17] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:18 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:18] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:18 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:18] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:18 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:18] "POST /autocomplete HTTP/1.1" 200 -
Jul 17 08:59:18 whoogle whoogle-search[493]: 192.168.1.2 - - [17/Jul/2022 08:59:18] "POST /search HTTP/1.1" 500 -
Jul 17 08:59:18 whoogle whoogle-search[493]: Traceback (most recent call last):
Jul 17 08:59:18 whoogle whoogle-search[493]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2095, in __call__
Jul 17 08:59:18 whoogle whoogle-search[493]:     return self.wsgi_app(environ, start_response)
Jul 17 08:59:18 whoogle whoogle-search[493]:   File "/usr/local/lib/python3.9/dist-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
Jul 17 08:59:18 whoogle whoogle-search[493]:     return self.app(environ, start_response)
Jul 17 08:59:18 whoogle whoogle-search[493]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2080, in wsgi_app
Jul 17 08:59:18 whoogle whoogle-search[493]:     response = self.handle_exception(e)
Jul 17 08:59:18 whoogle whoogle-search[493]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2077, in wsgi_app
Jul 17 08:59:18 whoogle whoogle-search[493]:     response = self.full_dispatch_request()
Jul 17 08:59:18 whoogle whoogle-search[493]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1525, in full_dispatch_request
Jul 17 08:59:18 whoogle whoogle-search[493]:     rv = self.handle_user_exception(e)
Jul 17 08:59:18 whoogle whoogle-search[493]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1523, in full_dispatch_request
Jul 17 08:59:18 whoogle whoogle-search[493]:     rv = self.dispatch_request()
Jul 17 08:59:18 whoogle whoogle-search[493]:   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1509, in dispatch_request
Jul 17 08:59:18 whoogle whoogle-search[493]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jul 17 08:59:18 whoogle whoogle-search[493]:   File "/usr/local/lib/python3.9/dist-packages/app/routes.py", line 79, in decorated
Jul 17 08:59:18 whoogle whoogle-search[493]:     _ = pickle.load(session_file)
Jul 17 08:59:18 whoogle whoogle-search[493]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
`

**Comment by DUOLabs333** [comment]
Can't reproduce.

**Comment by itmanagerro** [comment]
Problem is with sessions from /usr/local/lib/python3.9/site-packages/app/static/config/session/ 

Workaround is to remove all session files within and then should work... until next time
