### ISSUE TITLE
[BUG] ERROR:app:Exception on /config

### ISSUE THREAD

**Issue by mzch** [benbusby/whoogle-search#829]
**Describe the bug**

ERROR:app:Exception on /config

```
Aug 22 23:04:09 n06 start.sh[507]: ERROR:app:Exception on /config [POST]
Aug 22 23:04:09 n06 start.sh[507]: Traceback (most recent call last):
Aug 22 23:04:09 n06 start.sh[507]:   File "/srv/whoogle/.pyenv/versions/3.10.6/lib/python3.10/site-packages/flask/app.py", line
2525, in wsgi_app
Aug 22 23:04:09 n06 start.sh[507]:     response = self.full_dispatch_request()
Aug 22 23:04:09 n06 start.sh[507]:   File "/srv/whoogle/.pyenv/versions/3.10.6/lib/python3.10/site-packages/flask/app.py", line
1822, in full_dispatch_request
Aug 22 23:04:09 n06 start.sh[507]:     rv = self.handle_user_exception(e)
Aug 22 23:04:09 n06 start.sh[507]:   File "/srv/whoogle/.pyenv/versions/3.10.6/lib/python3.10/site-packages/flask/app.py", line
1820, in full_dispatch_request
Aug 22 23:04:09 n06 start.sh[507]:     rv = self.dispatch_request()
Aug 22 23:04:09 n06 start.sh[507]:   File "/srv/whoogle/.pyenv/versions/3.10.6/lib/python3.10/site-packages/flask/app.py", line
1796, in dispatch_request
Aug 22 23:04:09 n06 start.sh[507]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Aug 22 23:04:09 n06 start.sh[507]:   File "/srv/whoogle/.pyenv/versions/3.10.6/lib/python3.10/site-packages/app/routes.py", line
 79, in decorated
Aug 22 23:04:09 n06 start.sh[507]:     _ = pickle.load(session_file)
Aug 22 23:04:09 n06 start.sh[507]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 1: invalid continuation
byte
Aug 22 23:04:10 n06 start.sh[507]: WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the
URL manually please check your spelling and try again.
```

**To Reproduce**
1. Click 'configuration'
2. Set Country 'Japan'
3. Interface Language 'Japanese'
4. Click Apply

**Deployment Method**
- [ ] Heroku (one-click deploy)
- [ ] Docker
- [ ] `run` executable
- [x] pip/pipx
- [ ] Other: [describe setup]

**Version of Whoogle Search**
- [ ] Latest build from [source] (i.e. GitHub, Docker Hub, pip, etc)
- [x] Version 0.7.4
- [ ] Not sure

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Browser Chrome
 - Version 104.0.5112.101

**Additional context**
Python: 3.10.6
Server OS: Debian 11.4

**Comment by mzch** [comment]
I tried to search in Japanese, the same error occurred.

**Comment by mzch** [comment]
When I enabled only `Open Links in New Tab`, the following error happened.
```
Aug 22 23:21:37 n06 start.sh[507]: ERROR:app:Exception on /config [POST]
Aug 22 23:21:37 n06 start.sh[507]: Traceback (most recent call last):
Aug 22 23:21:37 n06 start.sh[507]:   File "/srv/whoogle/.pyenv/versions/3.10.6/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
Aug 22 23:21:37 n06 start.sh[507]:     response = self.full_dispatch_request()
Aug 22 23:21:37 n06 start.sh[507]:   File "/srv/whoogle/.pyenv/versions/3.10.6/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
Aug 22 23:21:37 n06 start.sh[507]:     rv = self.handle_user_exception(e)
Aug 22 23:21:37 n06 start.sh[507]:   File "/srv/whoogle/.pyenv/versions/3.10.6/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
Aug 22 23:21:37 n06 start.sh[507]:     rv = self.dispatch_request()
Aug 22 23:21:37 n06 start.sh[507]:   File "/srv/whoogle/.pyenv/versions/3.10.6/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
Aug 22 23:21:37 n06 start.sh[507]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
Aug 22 23:21:37 n06 start.sh[507]:   File "/srv/whoogle/.pyenv/versions/3.10.6/lib/python3.10/site-packages/app/routes.py", line 79, in decorated
Aug 22 23:21:37 n06 start.sh[507]:     _ = pickle.load(session_file)
Aug 22 23:21:37 n06 start.sh[507]: ValueError: could not convert string to int
Aug 22 23:21:37 n06 start.sh[507]: WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Comment by mzch** [comment]
Sorry, when I switched python to 3.11.0rc0, I've got no error.
