### ISSUE TITLE
[BUG] Firefox: WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

### ISSUE THREAD

**Issue by un99known99** [benbusby/whoogle-search#910]
Hi,

while using FF getting often error below (brave seems to be ok), I am switching back and fwd using options pics, video - time and quality filters - and so on, in between getting 

ERROR:app:Exception on /search [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pi/.local/lib/python3.9/site-packages/app/routes.py", line 112, in decorated
    return f(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/app/routes.py", line 59, in decorated
    return f(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/app/routes.py", line 304, in search
    response = search_util.generate_response()
  File "/home/pi/.local/lib/python3.9/site-packages/app/utils/search.py", line 149, in generate_response
    html_soup = content_filter.view_image(html_soup)
  File "/home/pi/.local/lib/python3.9/site-packages/app/filter.py", line 617, in view_image
    results_div = soup.find_all('div', attrs={'class': "nQvrDb"})[0]
IndexError: list index out of range
WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Regards,
Mike

**Comment by Moist-Cat** [comment]
I maanged to reproduce it with the last commit ( 7041b43db96142015df8d2b0170f0f2318c57c31 )

Configurations:
    Time period: last hour (as small as possible)
    Full Size Image Search: True

It seems it breaks when there are no images to display.
This could be fixed by adding some error handling to https://github.com/benbusby/whoogle-search/blob/main/app/filter.py#L600

In the meantime. Either disable Full Size image Search or increase the Time Period. I don't think this is related to the browser at all.

**Comment by un99known99** [comment]
Thanks for the reply, I checked in FF and in Brave, whereas Brave seems to be more “stable”, seems I couldn't reproduce the error within Brave - that's why my best guess was to be browser related ...

Will double-check with hint you gave in terms of the full size image and come back ...
