### ISSUE TITLE
[BUG] binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by un99known99** [benbusby/whoogle-search#987]
searching via whoogle, clicking in result list from ALL (ALLE) to PICTURES (BILDER):

![grafik](https://user-images.githubusercontent.com/1615207/232121701-43901278-032e-422e-b1e8-be59e4671504.png)

![grafik](https://user-images.githubusercontent.com/1615207/232121018-03070f80-3703-403b-b4f9-2a8e91d5b833.png)

same for "weiter" / continue, trying to see more search results:

![grafik](https://user-images.githubusercontent.com/1615207/232219468-fd1cc80b-3413-4423-b9a6-997914129a06.png)

Getting error in logfile:

pi@pihole:[/var/log] $ cat whoogle.log

ERROR:app:Exception on /search [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 1818, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/pi/.local/lib/python3.9/site-packages/flask/app.py", line 2309, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/pi/.local/lib/python3.9/site-packages/app/routes.py", line 158, in before_request_func
    g.user_config = g.user_config.from_params(g.request_params)
  File "/home/pi/.local/lib/python3.9/site-packages/app/models/config.py", line 143, in from_params
    params_new = self._decode_preferences(params['preferences'])
  File "/home/pi/.local/lib/python3.9/site-packages/app/models/config.py", line 214, in _decode_preferences
    brotli.decompress(urlsafe_b64decode(preferences.encode()))
  File "/usr/lib/python3.9/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/usr/lib/python3.9/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by un99known99** [comment]
Seems to be Firefox related, working with brave

**Comment by un99known99** [comment]
might be revealed again => https://github.com/benbusby/whoogle-search/issues/910

**Comment by un99known99** [comment]
Seems Whoogle not working properly together with Firefox, cant get the search work correctly, seems to be ok for Vivaldi and Brave for example.

**Comment by un99known99** [comment]
anyone able to help?

**Comment by benbusby** [comment]
Hi, sorry for the delay! I believe the issue you're encountering should be fixed now, although I wasn't able to reproduce it on my end unfortunately. The preferences string should be encoded correctly (and therefore have the correct padding), but perhaps Firefox is stripping the padding from the param?

In any case, padding is now manually appended to the end of the value, which should fix this for you. Let me know if I can help further.

**Comment by un99known99** [comment]
@benbusby - many thanks for the feedback, it is indeed a bit strange, other browser apart from FF (vivaldi, brave, etc.) are doing ok - on desktop, on mobile all are in fact OK, even FF  - so the fix you mentioned will be in 0.8.3?
